"""add Single column to Song model

Revision ID: 8a5fdae0b02b
Revises: 9bcb6253eb12
Create Date: 2022-04-12 19:11:07.924841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a5fdae0b02b'
down_revision = '9bcb6253eb12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('song', sa.Column('single', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('song', 'single')
    # ### end Alembic commands ###
