"""add slug to Album model

Revision ID: 9bcb6253eb12
Revises: e8c44f19f25b
Create Date: 2022-04-12 18:30:17.347244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bcb6253eb12'
down_revision = 'e8c44f19f25b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('album', sa.Column('slug', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('album', 'slug')
    # ### end Alembic commands ###
