"""add slug to Song model

Revision ID: e8c44f19f25b
Revises: f81eb5730a20
Create Date: 2022-04-12 18:29:28.530417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8c44f19f25b'
down_revision = 'f81eb5730a20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('song', sa.Column('slug', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('song', 'slug')
    # ### end Alembic commands ###
