"""add lenght column to Song

Revision ID: f81eb5730a20
Revises: b4cfcf113ff5
Create Date: 2022-04-11 20:01:19.537406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f81eb5730a20'
down_revision = 'b4cfcf113ff5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('song', sa.Column('length', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('song', 'length')
    # ### end Alembic commands ###
